### ISSUE TITLE
Feature: Proxy implementation

### ISSUE THREAD

**Issue by developervariety** [SmorcIRL/mail.tm#3]
Offer the availability to use a proxy with `HttpClient` instance. In my case, it would be to avoid the rate limits.

**Comment by SmorcIRL** [comment]
As i see, proxy can be specified when creating HttpClient instance, should allowing passing it in MailClient constructor solve the issue?

**Comment by developervariety** [comment]
> As i see, proxy can be specified when creating HttpClient instance, should allowing passing it in MailClient constructor solve the issue?

Yes sir!

**Comment by SmorcIRL** [comment]
Done, you can update now.
