### ISSUE TITLE
How to register?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SmorcIRL/mail.tm#4]
Hello:
I want to test temporary email functions with the repo.
But I can't figure out how to register.
I have done the following:
1. Create one WinForms App project (.Net 6.0)
2. Add nuget package:
PM> Install-Package SmorcIRL.TempMail -Version 2.0.1
3. The following is my C# code:
private async void Form1_Load(object sender, EventArgs e)
{    
MailClient client = new();    
await client.Register("pepethefrog@sad.me", "*password*");    
DomainInfo[] domains = await client.GetAvailableDomains();    
Debug.Print(domains.Length.ToString());
}
But the client.Register statment always failed.
I got error: 422.

I also tried the API playground from this URL:
https://api.mail.tm/

If I click on "Authorize" green button, if I input "pepethefrog@sad.me", I got message:
Authorized, 
Value for the Authorization header parameter.
Name: Authorization
In: header
Value: ******

But when I try to execute the command, as the following HTTP request:
curl -X 'POST' \
  'https://api.mail.tm/accounts' \
  -H 'accept: application/ld+json' \
  -H 'Authorization: pepethefrog@sad.me' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "address": "user@example.com",
  "password": "string"
}'

I got 422 error with the following message:
{
  "@context": "/contexts/ConstraintViolationList",
  "@type": "ConstraintViolationList",
  "hydra:title": "An error occurred",
  "hydra:description": "address: The domain \"example.com\" is not valid.\naddress: The username \"user\" is not valid.",
  "violations": [
    {
      "propertyPath": "address",
      "message": "The domain \"example.com\" is not valid.",
      "code": null
    },
    {
      "propertyPath": "address",
      "message": "The username \"user\" is not valid.",
      "code": null
    }
  ]
}
With the following Response headers
 access-control-allow-origin: * 
 cache-control: no-cache,private 
 content-length: 462 
 content-type: application/ld+json; charset=utf-8 
 date: Wed,11 May 2022 15:36:45 GMT 
 link: <https://api.mail.tm/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation",<https://mercure.mail.tm/.well-known/mercure>; rel="mercure" 
 server: Caddy 
 status: 422 Unprocessable Content 
 x-content-type-options: nosniff 
 x-frame-options: deny 

Let me know how I can use API or Playground to register.
Or, if I can skip register, and use API to create a temporary email account.
Then let me know how many domain I can choose?
Only this one: "scpulse.com"?
Thanks,

**Comment by SmorcIRL** [comment]
Creds used in the readme are just an example. There is a list of currently available domains that is refreshing regularly, so you firstly need to obtain it via GetAvailableDomains() and create your address based on it. Just read readme or check tests.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  From my C# code, 
DomainInfo[] domains = await client.GetAvailableDomains();
There is only one domain, right?

**Comment by SmorcIRL** [comment]
At least, service may add more.
