### ISSUE TITLE
Getting the body of mail

### ISSUE THREAD

**Issue by Adilx05** [SmorcIRL/mail.tm#5]
The version inside the nuget package does not have a method to retrieve the body of the email. I can only take it as an intro.

**Comment by SmorcIRL** [comment]
Yeah, as far as I can remember this is a limitation of the original api. I'll get a look a bit later.

**Comment by SmorcIRL** [comment]
So, as I said, that's how their api works. Check [this](https://docs.mail.tm/#get-sourcesid) and [this](https://en.wikipedia.org/wiki/Email#Message_body). Seems you need to parse the source string by yourself. Just check how the mail looks like in the browser using devtools and get the data you need from the corresponding tag (don't forget about encoding).

**Comment by Adilx05** [comment]
> So, as I said, that's how their api works. Check [this](https://docs.mail.tm/#get-sourcesid) and [this](https://en.wikipedia.org/wiki/Email#Message_body). Seems you need to parse the source string by yourself. Just check how the mail looks like in the browser using devtools and get the data you need from the corresponding tag (don't forget about encoding).

I found a solution myself for this. I receive the entire mail and then delete the part up to the <div>.

`private async Task<string> GetMessageSourceAsync(string messageId)
        {
            MessageSource source = await client.GetMessageSource(messageId);
            string mailData = source.Data;
            return mailData;
            
        }`
