### ISSUE TITLE
Method Register always throw error 401

### ISSUE THREAD

**Issue by TiepHoangDev** [SmorcIRL/mail.tm#6]
Can you check api or code for method Register. It always return error 401. thank you!
27/09/2023

**Comment by SmorcIRL** [comment]
Yeah, I'm not even sure they haven't changed the API in the last two years. I'll check

**Comment by SmorcIRL** [comment]
Works fine with mail.tm for me, but throws an error (422) for mail.gw. Can you share your code @TiepHoangDev ?

**Comment by TiepHoangDev** [comment]
I discovered that address must be in lowercase, thanks for your library!
